CREATE DATABASE IF NOT EXISTS femanic_co
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE femanic_co;

CREATE TABLE IF NOT EXISTS usuario (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(120) NOT NULL,
  EMAIL VARCHAR(180) NOT NULL UNIQUE,
  IDADE TINYINT UNSIGNED NOT NULL,
  SENHA VARCHAR(255) NOT NULL,
  RECEBER BOOLEAN NOT NULL DEFAULT FALSE,
  TERMOS BOOLEAN NOT NULL DEFAULT FALSE,
  CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS produto (
  IDPROD INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(160) NOT NULL,
  PRECO DECIMAL(10, 2) NOT NULL,
  CLASSE VARCHAR(60),
  IMAGEM VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS enderecos (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  RUA VARCHAR(180) NOT NULL,
  NUMERO VARCHAR(20) NOT NULL,
  BAIRRO VARCHAR(120) NOT NULL,
  COMPLEMENTO VARCHAR(120),
  ESTADO CHAR(2) NOT NULL,
  CIDADE VARCHAR(120) NOT NULL,
  CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS carrinhoprod (
  ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ID_CARRINHO BIGINT UNSIGNED NOT NULL,
  PRODUTO VARCHAR(160) NOT NULL,
  PRECO DECIMAL(10, 2) NOT NULL,
  QUANTIDADE INT UNSIGNED NOT NULL,
  SUBTOTAL DECIMAL(10, 2) GENERATED ALWAYS AS (PRECO * QUANTIDADE) STORED,
  CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

